### ISSUE TITLE
URLImageProvider - affichage des smileys téléchargés

### ISSUE THREAD

**Issue by AnaelMobilia** [AnaelMobilia/NextINpact-Unofficial#128]
Si une image n'est pas présente en cache, on la DL.
Malgré plusieurs essais (cf #126), impossible de rafraîchir l'image déjà affichée.
Par contre, pas de problèmes pour l'afficher si défilement de la liste de commentaires...

**Comment by Dostoi** [comment]
Est ce que c'est par rapport aux smiley remplacés par le logo de Nextinpact au début ?

**Comment by AnaelMobilia** [comment]
Tout à fait !
Si je n'ai pas le smiley en cache , je lance un téléchargement.
Je sais être notifié de la fin du téléchargement, mais je n'arrive pas à forcer le rafraicchissement de l'interface (celle que l'utilisateur voit)
