### ISSUE TITLE
Options - synchronisation des commentaires

### ISSUE THREAD

**Issue by AnaelMobilia** [AnaelMobilia/NextINpact-Unofficial#136]
Deux choses :
  - Permettre un DL des commentaires à l'appartition de l'article
  - Si le nb de commentaires évolue, télécharger les commentaires non présents pour le moment
  - Télécharger immédiatement les smileys

**Comment by Dostoi** [comment]
C'est possible d'ajouter une option pour faire la syncrho que par wifi ?

**Comment by AnaelMobilia** [comment]
Je ne vois pas ce que tu veux dire :
Par défaut, si une connexion data et une connexion wifi sont présentes, Android utilisera la connexion WiFi.

Les synchros sont lancées par l'action de l'utilisateur qui clique sur le bouton de synchronisation.

Si l'utilisateur lance une synchro alors qu'il ne veux pas la lancer... je ne comprends pas :-)

**Comment by Dostoi** [comment]
Non pas dans ce sens la ^^
Avoir une option permettant de choisir si les commentaires seront synchronisés avec n'importe quel type de connexion ou que avec une connexion wifi

**Comment by AnaelMobilia** [comment]
La synchronisation est effectuée sur demande de l'utilisateur, toujours dans l'application. (elle n'est plus en place sur les versions beta, d'où le présent ticket ;-))

Tu veux peut-être parler de la fonctionnalité de "chargement en continu des commentaires" qui charge les commentaires au fil et à mesure de la lecture ?

**Comment by AnaelMobilia** [comment]
Doublon de #116

**Comment by Dostoi** [comment]
On se comprend pas du tout x)

Alors je ne sais pas comment cela fonctionnait avant mais en fait ce dont je parle c'est la possibilité de télécharger et afficher tous les commentaire d'un article choisi d'un coup et pas en défilant.
En fait ajouter un bouton dans la section commentaire à coté de celui qui permet de recharger, pour télécharger tous les commentaires de l'article d'un coup.

J'espère que je suis plus clair cette fois ci ^^

**Comment by AnaelMobilia** [comment]
Pour éclaircir :
  - #116 : permettre de synchroniser (automatiquement) tous les commentaires de tous les articles
  - #71 : permettre de télécharger (manuellement) tous les commentaires d'un article précis

Est-ce plus clair ?

**Comment by Dostoi** [comment]
Ha oui parfait, je parlais de la 71 en fait mais sans le savoir ^^
