### ISSUE TITLE
Icone avant chaque article

### ISSUE THREAD

**Issue by Dostoi** [AnaelMobilia/NextINpact-Unofficial#138]
Au début de chaque article (avant le titre), il y a une icône présente. Elle correspond au thème de l'article mais je ne sais pas si elle devrait être présente

**Comment by AnaelMobilia** [comment]
Ni pour, ni contre...
Je veux refondre cette vue également dans une version ultérieure pour arrêter d'utiliser webkit pour l'affichage (lancement du navigateur). Je veux passer à de la gestion directe (comme pour les commentaires & co)
