### ISSUE TITLE
Icône abonné pas présente

### ISSUE THREAD

**Issue by Dostoi** [AnaelMobilia/NextINpact-Unofficial#139]
Sur les articles réservés aux abonnés (dans la liste des articles), l'icône n'est pas présente en dessous du titre de l'article pour la news sur spotify (http://www.nextinpact.com/news/92858-pourquoi-spotify-n-integre-pas-encore-chromecast.htm)

**Comment by AnaelMobilia** [comment]
Hello,

As-tu un titre d'article ?

**Comment by AnaelMobilia** [comment]
Exemple : [Interview] Pourquoi les greffiers s'opposent à la mise en Open Data...

**Comment by Dostoi** [comment]
ça ne s'affiche pas pour moi

![screenshot_2015-01-28-08-09-19](https://cloud.githubusercontent.com/assets/7694864/5934192/ef73d8fc-a6cb-11e4-941f-35663866fa5b.png)

**Comment by Dostoi** [comment]
En fait l'icône s'affiche au 1er chargement mais quand je relance l'app après ça, il n'est plus présent.

**Comment by AnaelMobilia** [comment]
Les sous-titres ne s'affichent que si ton écran est suffisament large.
Sinon, pas d'affichages, pour éviter d'avoir 5 à 6 lignes de textes (ce qui diviserait par deux le nombre d'articles affichés !)

**Comment by Dostoi** [comment]
ça ne devrait pas s'afficher quand même si je tourne l'écran ?

**Comment by AnaelMobilia** [comment]
J'utilise du layout-normal et layout-large (donc auto-géré par Android directement) :
```
As you design your UI for different screen sizes, you'll discover that each design requires a minimum amount of space. So, each generalized screen size above has an associated minimum resolution that's defined by the system. These minimum sizes are in "dp" units—the same units you should use when defining your layouts—which allows the system to avoid worrying about changes in screen density.

  - xlarge screens are at least 960dp x 720dp
  - large screens are at least 640dp x 480dp
  - normal screens are at least 470dp x 320dp
  - small screens are at least 426dp x 320dp

Note: These minimum screen sizes were not as well defined prior to Android 3.0, so you may encounter some devices that are mis-classified between normal and large. These are also based on the physical resolution of the screen, so may vary across devices—for example a 1024x720 tablet with a system bar actually has a bit less space available to the application due to it being used by the system bar.
```

Sur mon téléphone en 4", je tombe en "normal" (sans les sous titres), avec la tablette en 8", je tombe en "large" (avec les sous-titres).

Quel est ton modèle de device ?

**Comment by Dostoi** [comment]
4.5" du coup je ne les ai pas en vue verticale mais je me demandais si c'était censé s'afficher en vue horizontale

**Comment by AnaelMobilia** [comment]
L'écran n'est pas assez grand du coup :/
L'idée est que la taille de la miniature d'un article correspond à 3 lignes de textes.
Une ligne de titre, une ligne (heure, abonné, commentaires).

Si l'écran est assez grand, se rajoute la ligne de sous-titre.

Sur mon 4", les titres prenent souvent deux lignes => mettre les sous-titres ferait que chaque article affiché dans la liste prendrait quasiment la place de deux articles actuels.
Ca ferait quand même une perte de place ;)

Je pense qu'en 5" ça doit passer... mais je n'ai jamais pu tester ! :)
