### ISSUE TITLE
écran blanc à la place de l'article

### ISSUE THREAD

**Issue by Dostoi** [AnaelMobilia/NextINpact-Unofficial#150]
L'article sur facebook (http://www.nextinpact.com/news/92901-facebook-en-2014-139-milliard-dutilisateurs-et-293-milliards-benefices.htm) ne s'affiche pas, il y a un écran blanc à la place.
On peut quand même accéder aux commentaires

**Comment by AnaelMobilia** [comment]
Plus présent en 1.8.2+ => certainement lié à un bug du parseur à l'époque
