### ISSUE TITLE
Gestion des téléchargements des ressources

### ISSUE THREAD

**Issue by Dostoi** [AnaelMobilia/NextINpact-Unofficial#155]
La miniature pour la news sur la sacem (http://www.nextinpact.com/news/93019-la-sacem-veut-revoir-l-affectation-redevance-pour-copie-privee.htm) ne s'affiche pas

**Comment by AnaelMobilia** [comment]
As-tu activé le mode debug dans les options ?
As-tu eu un message d'erreur ?

Sur ma tablette, la miniature s'affiche bien (je pense que c'est un problème de téléchargement).
Du coup tu as bien une icône NXI ?

**Comment by Dostoi** [comment]
Oui mais j'ai pas fait attention si il y avait un message au 1er chargement et après il n'y en a pas.

Oui à la place j'ai l'icône de NXI.

**Comment by AnaelMobilia** [comment]
Parfait, le problème est correctement attrapé !

Il n'y a pas grand chose de plus à faire. Tout au plus je pourrais mettre l'icône dans une liste de trucs à dl ?

**Comment by Dostoi** [comment]
Aucune idée ^^
Après c'est pas vraiment un problème grave, si ça ne se reproduit pas pas besoin de s'embêter.

**Comment by AnaelMobilia** [comment]
Oui, le problème n'est pas grave puisqu'il ne fait ni planter l'application, nicause de réel souci à l'utilisation de l'application.

Je pourrais facilement lancer le dl de l'image lorsque je constate qu'elle manque (au moment de l'affichage, cf https://github.com/AnaelMobilia/NextINpact-Unofficial/blob/master/src/com/pcinpact/adapters/ItemsAdapter.java#L218 ) puisque j'affiche une image "par défaut".

Mon interrogation est sur le droit de lancer des DL à n'importe quel moment ?
L'application est détaillée comme permettant de la consultation hors ligne => je m'attendrais à ce qu'elle ne fasse pas des DL sauvage à tout va.
Mais j'ai peut-être une mauvaise vision du marché des forfaits d'aujourd'hui ^-^

**Comment by Dostoi** [comment]
J'ai trouvé pourquoi ça fait ça.
En lançant le chargement de nouvelles news, si l'application est quitté avant que les nouvelles news s'affichent, lors du prochain chargement elles vont s'afficher sans la  miniature. Ou un truc dans le genre, ça me l'a refait tout à l'heure quand j'ai essayé d'en charger des nouvelles mais comme je captais mal et que ça tournait pendant longtemps, j'ai quitté et en relançant l'appli plus tard j'avais les news sans les miniatures

**Comment by Dostoi** [comment]
ça ne l'avait pas fait avec le 1er mais pour les 3 de ce matin dont la miniature ne s'affiche pas, il n'y a pas le contenu de l'article non plus.

**Comment by Dostoi** [comment]
Salut,

C'est possible de relancer le téléchargement à la prochaine synchro si il y a une erreur entre deux ? Car pour l'instant si il y a une erreur, il n'y a pas moyen de récupérer quand même l'article.

Ha oui pourquoi pas, ça ne pourrait pas résoudre le problème d'affiche des smileys en même temps ?

**Comment by AnaelMobilia** [comment]
TODO : suppression des articles dont le contenu n'a pas été téléchargé de la liste des articles.
Tenter un DL à nouveau avant de les supprimer

**Comment by Dostoi** [comment]
Ils vont être retéléchargé à la prochaine synchro une fois supprimé ou pas ?

**Comment by AnaelMobilia** [comment]
Yep !

**Comment by Dostoi** [comment]
Nickel alors ^^

**Comment by AnaelMobilia** [comment]
Le téléchargement des smileys au premier lancement fait crash l'application (128 threads en parallèle maximum, dl de ~300 smileys). Pas possible.

**Comment by Dostoi** [comment]
Ha mince, on fera avec alors ^^
