### ISSUE TITLE
Ajout d'un bouton pour télécharger tous les commentaires d'un coup

### ISSUE THREAD

**Issue by Dostoi** [AnaelMobilia/NextINpact-Unofficial#162]
Ajouter un bouton dans le menu des commentaires pour télécharger tous les commentaires présent d'un coup au lieu de le faire au fur et à mesure.

**Comment by AnaelMobilia** [comment]
Doublon de #71

**Comment by Dostoi** [comment]
Ha mince désolé pour les doublons

**Comment by AnaelMobilia** [comment]
;-)
