### ISSUE TITLE
Bug d'affichage

### ISSUE THREAD

**Issue by Dostoi** [AnaelMobilia/NextINpact-Unofficial#180]
Juste pour dire qu'il existe. En gros la barre de la date ne s'affiche pas totalement quand on fait une synchro mais ça n'arrive qu'une fois de temps en temps, je n'ai pas réussi à trouver de méthode pour le faire apparaître à chaque fois

![screenshot_2015-04-07-11-52-06](https://cloud.githubusercontent.com/assets/7694864/7021952/221826b4-dd27-11e4-927d-b46e09548b23.png)

Rien à voir mais je me demandais si c'était normal que je n'ai pas eu de mise à jour depuis un moment alors que tu mets toujours à jour l'appli assez souvent ?

**Comment by AnaelMobilia** [comment]
Effectivement, il est connu celui là :-/

Constates-tu alors un lancement du refraichissement de la liste d'articles (le téléchargement toussa) quand tu scrolles vers le bas ?

J'ai bien peur qu'il ne s'agisse d'un bug au niveau android même, donc hors de ma portée ;-)

(pour les mises à jour, chaque fois que je publie une nouvelle release sur le play store, je la taggue sur github -> https://github.com/AnaelMobilia/NextINpact-Unofficial/releases .
En ce moment, je suis sur un gros truc dans la reprise de la liste des articles, et j'attends d'avoir stablilisé l'application avant de publier la mise à jour qui devrait nous conduire à la v2.0 ;-) )

**Comment by Dostoi** [comment]
J'ai pas fait attention en scrollant vers le bas, je vais regarder la prochaine fois.

Pas grave alors ^^

D'accord :)

**Comment by AnaelMobilia** [comment]
Lié à un problème dans le code android.
Pourrait être corrigé par un passage à une version supérieurs de supportv4 / appcompatv7
=> La suite se passera dans #174 

Merci :-)
