### ISSUE TITLE
Afficher les images des tweet affichés dans les articles

### ISSUE THREAD

**Issue by Dostoi** [AnaelMobilia/NextINpact-Unofficial#204]
Salut, 
Je me demandais s'il est possible d'afficher directement les images des tweets contenues dans les articles ?
Pour l.instant on doit cliquer dessus et les afficher dans le navigateur
Merci d'avance :)

**Comment by AnaelMobilia** [comment]
Hello,

Malheureusement, les images sont chargées directement dans une iframe chargeant le contenu depuis twitter.
En fonction des journalistes, ils mettent soit des captures d'écran du tweet (auquel cas le tweet apparaît), soit une iframe vers twitter pour afficher le lien, auquel cas... :/

**Comment by Dostoi** [comment]
Ah mince dommage. Pas grave alors ^^
