### ISSUE TITLE
Impossible de charger plus de 9 commentaires

### ISSUE THREAD

**Issue by Dostoi** [AnaelMobilia/NextINpact-Unofficial#205]
Sur cette news : https://m.nextinpact.com/news/100932-deux-deputes-s-attaquent-au-phenomene-pokemon-go.htm
Je ne peux pas charger plus que les 9 premiers commentaires

**Comment by AnaelMobilia** [comment]
Concrètement, il y a un problème chez NXI qui a enregistré deux fois le commentaire 5 (et donc n'arrive pas à atteindre le commentaire numéro 10 sur la page)...

**Comment by Dostoi** [comment]
C'est pas la 1ere fois de mémoire mais c'est super rare donc c'est pas trop embêtant

**Comment by AnaelMobilia** [comment]
Arf, merci du retour !
Si c'est amené à devenir régulier, il vaut mieux que je reprenne le système de gestion de stockage des commentaires :-)
Je faisais confiance au numéro affiché, mais il va falloir utiliser l'ID (non affiché) du commentaire, ça résoudra tout ^-^

**Comment by AnaelMobilia** [comment]
Note : c'est ce que j'ai fait : utilisation du UUID du commentaire au lieu de l'ID affiché car problème venant régulièrement.
Mise à jour du schéma de la BDD + migration des données
