### ISSUE TITLE
publication sur F-DROID

### ISSUE THREAD

**Issue by tpeg5stan** [AnaelMobilia/NextINpact-Unofficial#222]
Bonjour,

L'application est sous licence GPL-3, donc compatible avec les conditions  de F-DROID, le market d'applications libres/open-source pour Android. Est-il possible de proposer cette application à F-DROID ? Je n'utilise pas de google apps/google play services, donc il faut chercher l'apk à la main, ce qui est un peu dommage.

Apparemment, il faut commencer par aller ici : https://f-droid.org/forums/forum/submission-queue/

**Comment by AnaelMobilia** [comment]
Hello,

L'application avait déjà été proposée par un utilisateur, sans suite côté F-DROID.

Peux-tu voir pour leur re-proposer l'application ?

Bonne soirée,
Anael

**Comment by tpeg5stan** [comment]
C'est fait ici : https://gitlab.com/fdroid/rfp/issues/147

J'attends voir leurs retours...

S'il n'y avait pas eu de retours la dernière fois, ce critères avait-il été respecté : [*] The original app author has been notified (and supports the inclusion). ? Si tu n'avais pas été notifié, peut-être qu'ils n'ont pas su continuer....

**Comment by tpeg5stan** [comment]
Génial, ça a été publié.

Bon, en espérant que ça augmentera le nombre de téléchargements...

(tu peux fermer le ticket je pense)

**Comment by AnaelMobilia** [comment]
Thanks ! :)
