### ISSUE TITLE
Chargement des commentaires

### ISSUE THREAD

**Issue by floviolleau** [AnaelMobilia/NextINpact-Unofficial#228]
Bonjour,

Merci pour le maintien de cette application très pratique et de partager le code ici ! 👍

Depuis la dernière version sur le play store (2.2.6), les commentaires ne se chargent plus.

Pouvez-vous corriger ?

Merci par avance.

**Comment by AnaelMobilia** [comment]
Hello,

J'avais déjà constaté ce souci hier soir.
Il y a systématiquement une erreur 500 à l'affichage des commentaires, idem en version mobile (m.nextinpact.com)

J'ai ouvert [un ticket sur le dépôt de NXI](https://github.com/NextINpact/nxiv6/issues/121), il n'y a plus qu'à attendre qu'ils corrigent sur leur serveur...

Merci pour le report ! ;)

Bonne journée,
Anael

**Comment by AnaelMobilia** [comment]
Problème résolu par NXI, tout recfonctionne sur l'application :)
