### ISSUE TITLE
Prise en charge du masquage des publicités rédactionnelles

### ISSUE THREAD

**Issue by CaseOf** [AnaelMobilia/NextINpact-Unofficial#252]
Bonjour,
Comme chacun doit probablement le savoir maintenant, NextInpact s’est lancé dans les publicités rédactionnelles. Ils proposent néanmoins de masquer ces publicités aux membres abonnés.
Actuellement, l’application ne masque pas ces publicités lorsque l’on est connecté avec un compte abonné.
Serait-il possible d’ajouter cette possibilité ?

**Comment by AnaelMobilia** [comment]
Hello,

Oui ça devrait être possible, elles ont l'air de se démarquer en partie en HTML !

Je regarde ça à l'occasion !

**Comment by CaseOf** [comment]
merci :+1: :1st_place_medal:

**Comment by AnaelMobilia** [comment]
@CaseOf La version 2.4.0 est publiée en beta sur le Play Store ;-)

**Comment by CaseOf** [comment]
Je n'ai pas de compte Google, est-il possible de la télécharger quand même? J'utilise Aurora Store et F-Droid sur mon ordiphone

**Comment by AnaelMobilia** [comment]
Je vois deux possibilités dans ce cas là :
  - Attendre quelques jours, le temps que F-Droid détecte la nouvelle version, la compile et la publie sur leur site (ça me semble le plus simple en gestion de mise à jour maintenant & future ;-))
A priori ça prend 2-3 jours quand je compare la date de publication de la release sur GitHub & celle qu'ils effectuent sur leur site.
  - Installer l'application depuis le fichier de release que je mets sur GitHub (https://github.com/AnaelMobilia/NextINpact-Unofficial/releases/tag/v2.4.0 => fichier app-release.apk), ce qui implique d'autoriser l'installation d'applications depuis des sources inconnues...

**Comment by CaseOf** [comment]
Entendu, je vais attendre de voir dans la semaine si la version de F-Droid arrive, s'ils trainent un peu, je prendrai la version ici sur GitHub ;)
