### ISSUE TITLE
NextInpact v7

### ISSUE THREAD

**Issue by CaseOf** [AnaelMobilia/NextINpact-Unofficial#261]
Bonjour,
La v7 n'est pas encore tout à fait finalisée mais elle sera mise en ligne pour tous au mois d'août en prod. La bêta est accessible aux abonnés.
L'application est elle compatible ou des ajustements seront nécessaires?

**Comment by AnaelMobilia** [comment]
Bonjour @CaseOf 
C'est quelque chose que je suis en ce moment.
Aujourd'hui, l'application se base sur le site mobile (m.nextinpact.com) pour parser le contenu HTML et le synchroniser.
A priori l'équipe NXI devrait arrêter de maintenir ce site... mais rien n'est dit à ce sujet pour autant par l'équipe NXI ;-)

Je pense qu'une nouvelle version de l'application sera nécessaire pour l'utilisation de la v7 !

Ils ont l'air d'utiliser les URL suivantes :
  - Liste des articles via https://api-v1-beta.nextinpact.com/api/v1/SimpleContent/list
  - Articles via https://api-v1-beta.nextinpact.com/api/v1/SimpleContent/21175
  - Commentaires via https://api-v1-beta.nextinpact.com/api/v1/Commentaire/list?ArticleId=21175

Sur IH, ils sont partis sur : 
  - Liste des articles : https://api-v1.inpact-hardware.com/api/v1/SimpleContent/list?Page=0&NoPinned=true&Nb=25
  - Articles : https://api-v1.inpact-hardware.com/api/v1/SimpleContent/1965
  - Commentaires : https://api-v1.inpact-hardware.com/api/v1/Commentaire/list?ArticleId=1965

**Comment by AnaelMobilia** [comment]
Des changements sont à effectuer, voir la branche v7 (en cours de développement)

**Comment by CaseOf** [comment]
Merci pour tout ce travail 😊👍
La v7 est déjà en ligne 😬
Du coup l'app ne parvient plus à récupérer les articles en l'état en effet.
J'attend avec impatience la mise à jour 😛
Mais pas de précipitation, le code de l'app se bonifie avec le temps 😄

**Comment by AnaelMobilia** [comment]
@CaseOf je viens de sortir une version 2.5.0 en beta test, elle prend en charge la v7 (et INpact Hardware également :-))

Elle sera dispo dans quelques jours sur F-droid (le temps qu'ils détectent la release et la compile) et à un moment dans le Play Store (le temps que les équipes Google valide la release) ;-)

**Comment by CaseOf** [comment]
Cool ! Vivement :)
