### ISSUE TITLE
#LeBrief agrégé

### ISSUE THREAD

**Issue by BhasherBEL** [AnaelMobilia/NextINpact-Unofficial#302]
Il pourrait être intéressant d'avoir une option pour avoir #LeBrief en agrégé (comme c'est possible en RSS) plutôt que chaque news indépendamment.

**Comment by AnaelMobilia** [comment]
Hello @BhasherBEL,

Merci pour cette demande que je comprends, mais qui ne sera pas mise en oeuvre pour deux raisons : 
  - L'application est basée sur le retour de l'API en v7, dans laquelle chaque article des news est indépendant. Ce changement impliquerait également de retravailler le stockage en base de données.
  - La gestion des commentaires serait spécifique à cet article (ils sont égalements basés sur l'API qui utilise l'ID de chaque article).

Si c'est le retour à la liste des articles qui est embêtante, il est possible d'utiliser le slider gauche/droite pour "glisser" d'un article à un autre rapidement.

Bonne journée,
Anael
