### ISSUE TITLE
Paramètres en mode sombre

### ISSUE THREAD

**Issue by BhasherBEL** [AnaelMobilia/NextINpact-Unofficial#303]
Lorsque le mode sombre est activé, le menu en haut a droite reste en thème blanc, et le texte des paramètres reste noir. Voir screenshot ci-après.

![Screenshot_20220127-230335_INpact_Actualités_informatiques](https://user-images.githubusercontent.com/45831883/151451331-36e25ab3-463b-436d-909b-e38e1f852925.png)
![Screenshot_20220127-230346_INpact_Actualités_informatiques](https://user-images.githubusercontent.com/45831883/151451335-a4f657bc-0360-4b8b-85c3-8c2c07fca58f.png)

**Comment by AnaelMobilia** [comment]
Le menu est maintenant cohérent avec la barre d'action :
![image](https://user-images.githubusercontent.com/6187125/224197284-f5643814-fd5d-493a-8ef6-63680adcaaf1.png)
