### ISSUE TITLE
Plus de mise à jour de contenu sur l'application ?

### ISSUE THREAD

**Issue by tifriis208** [AnaelMobilia/NextINpact-Unofficial#320]
Bonjour,

Tout d'abord, merci pour cette application, qui me permet de lire hors ligne les articles de next.
Depuis quelques jours, elle ne semble plus récupérer le contenu du site.
J'ai tenté une réinstallation, toujours le même problème (je vois bien la requêtes vers next cote DNS). Une idée ?

![Screenshot_20241121-231823](https://github.com/user-attachments/assets/abd3b859-9e2f-4aa1-84ba-a46c0200cf4f)

Merci !

**Comment by AnaelMobilia** [comment]
Hello @tifriis208 ,

L'API WordPress n'est plus disponible depuis mercredi à priori, entraînant avec elle la possibilité pour l'application de récupérer les contenus (erreurs 404 sur les pages de l'API).

J'ai contacté l'équipe de Next pour savoir si cela était volontaire et / ou si une solution de contournement était possible :-)

A suivre donc !

Bonne journée,
Anael

**Comment by tifriis208** [comment]
Merci pour l'info ! On croise les doigts :)

**Comment by AnaelMobilia** [comment]
L'API WP n'est plus disponible publiquement, je vais faire évoluer le parseur pour scrapper directement le site internet -> #321 :)
