### ISSUE TITLE
Optimisation de l'empreinte mémoire de l'application

### ISSUE THREAD

**Issue by AnaelMobilia** [AnaelMobilia/NextINpact-Unofficial#93]
http://developer.android.com/reference/java/lang/ref/WeakReference.html

Voir là où ce genre d'objet est utilisable pour optimiser la libération de mémoire de l'application

**Comment by AnaelMobilia** [comment]
http://android-developers.blogspot.fr/2009/01/avoiding-memory-leaks.html

**Comment by AnaelMobilia** [comment]
Passage en hors branche pour conserver les liens...

**Comment by Dostoi** [comment]
Par rapport à ça (bon plus ou moins je pense ^^). Est ce que les articles sont supprimés une fois qu'ils dépassent la date/quantité nécessaire pour être affiché. Sur mon ancien téléphone avec l'application (bon ça remontait à un moment donc je ne sais pas si c'est encore d'actualité), l'application ne supprimait jamais les articles donc ça finissait par prendre pas mal de place.

**Comment by AnaelMobilia** [comment]
C'est #109 dont tu parles plutôt. (oui, c'est déjà mis en place ;-))

Ce ticket est plus pour la quantité de RAM prise par l'application lors de son exécution, et la traque des morceaux de code qui restent chargés alors que non utiles.

**Comment by Dostoi** [comment]
Ha oui j'avais raté celui la. Du coup c'est bon tu t'en occupes déjà :)
