### ISSUE TITLE
Chargement continu des commentaires ne fonctionne pas

### ISSUE THREAD

**Issue by Dostoi** [AnaelMobilia/NextINpact-Unofficial#99]
Le chargement continu des commentaires ne fonctionne pas pour la news sur Spartan du vendredi 02
On peut quand même les charger en appuyant sur télécharger les commentaires suivants

**Comment by AnaelMobilia** [comment]
URL article : http://m.nextinpact.com/news/91587-spartan-nouveau-navigateur-dans-windows-10-pas-si-vite.htm

A tester

**Comment by AnaelMobilia** [comment]
@Dostoi : je cherche à monter un petit groupe de testeurs pour les futures versions de l'appli (dont la 1.8.0 que je suis en train de développer en ce moment qui va amener de très gros changements sous le capot (performances et stabilité de l'application). Tu serais intéressé pour y participer ?

**Comment by Dostoi** [comment]
Ha oui pas de soucis :)

**Comment by AnaelMobilia** [comment]
Cool :-)
Je te tiens au courant !

**Comment by AnaelMobilia** [comment]
@Dostoi peux-tu me donner l'adresse mail de ton compte Google attaché à ton device pour que je te rajoute dans les destinataires d'une version de test de la 1.8.0 dans quelques jours ? (contrib@anael.eu)

Merci !

**Comment by AnaelMobilia** [comment]
Fixé dans un des commit de la v1.8.0
